import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { store } from "../Redux/app/store";
import { Provider } from "react-redux";

import "../style/global.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Provider store={store}>
        <Header />
        <Head>
          <title>CodesWears</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo-sm.png" />
        </Head>
        <Component {...pageProps} />
        <Footer />
      </Provider>
    </>
  );
}

export default MyApp;
