import Head from "next/head";
import "../style/global.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>CodesWears</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-sm.png" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
